apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
      version: green
  template:
    metadata:
      labels:
        app: devsecops
        version: green
    spec:
      containers:
      - name: app
        image: devsecopsacr14246.azurecr.io/devsecops-app:v3
        ports:
        - containerPort: 5000
