apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
      version: blue
  template:
    metadata:
      labels:
        app: devsecops
        version: blue
    spec:
      containers:
      - name: app
        image: myapp:blue
        ports:
        - containerPort: 5000
